# DataDog Cluster Agent for Advanced Kubernetes Monitoring
apiVersion: apps/v1
kind: Deployment
metadata:
  name: datadog-cluster-agent
  namespace: datadog
  labels:
    app: datadog-cluster-agent
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: datadog-cluster-agent
  template:
    metadata:
      labels:
        app: datadog-cluster-agent
      name: datadog-cluster-agent
    spec:
      serviceAccountName: datadog-cluster-agent
      containers:
      - image: gcr.io/datadoghq/cluster-agent:7.48.0
        imagePullPolicy: Always
        name: cluster-agent
        env:
          - name: DD_API_KEY
            valueFrom:
              secretKeyRef:
                name: datadog-secret
                key: api-key
          - name: DD_APP_KEY
            valueFrom:
              secretKeyRef:
                name: datadog-secret
                key: app-key
          - name: DD_CLUSTER_AGENT_TOKEN_NAME
            value: "datadog-cluster-agent-token"
          - name: DD_COLLECT_KUBERNETES_EVENTS
            value: "true"
          - name: DD_CLUSTER_NAME
            value: "enterprise-data-platform"
          - name: DD_SITE
            value: "datadoghq.com"
          - name: DD_CLUSTER_AGENT_KUBERNETES_SERVICE_NAME
            value: "datadog-cluster-agent"
          - name: DD_CLUSTER_AGENT_AUTH_TOKEN
            valueFrom:
              secretKeyRef:
                name: datadog-cluster-agent-token
                key: token
          - name: DD_KUBE_RESOURCES_NAMESPACE
            value: "datadog"
          - name: DD_ORCHESTRATOR_EXPLORER_ENABLED
            value: "true"
          - name: DD_CLUSTER_AGENT_COLLECT_KUBERNETES_TAGS
            value: "true"
          - name: DD_ADMISSION_CONTROLLER_ENABLED
            value: "true"
          - name: DD_ADMISSION_CONTROLLER_WEBHOOK_NAME
            value: "datadog-webhook"
          - name: DD_ADMISSION_CONTROLLER_MUTATE_UNLABELLED
            value: "true"
          - name: DD_ADMISSION_CONTROLLER_SERVICE_NAME
            value: "datadog-cluster-agent-admission-controller"
          - name: DD_EXTERNAL_METRICS_PROVIDER_ENABLED
            value: "true"
          - name: DD_EXTERNAL_METRICS_PROVIDER_WPA_CONTROLLER
            value: "true"
          - name: DD_EXTERNAL_METRICS_PROVIDER_USE_DATADOGMETRIC_CRD
            value: "true"
          - name: DD_CLUSTER_CHECKS_ENABLED
            value: "true"
          - name: DD_EXTRA_CONFIG_PROVIDERS
            value: "kube_endpoints kube_services"
          - name: DD_EXTRA_LISTENERS
            value: "kube_endpoints kube_services"
        ports:
        - containerPort: 5005
          name: agentport
          protocol: TCP
        - containerPort: 443
          name: webhookport
          protocol: TCP
        resources:
          requests:
            cpu: "200m"
            memory: "256Mi"
          limits:
            cpu: "200m"
            memory: "512Mi"
        livenessProbe:
          httpGet:
            path: /live
            port: 5005
          initialDelaySeconds: 15
          periodSeconds: 15
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /ready
            port: 5005
          initialDelaySeconds: 15
          periodSeconds: 15
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
        volumeMounts:
        - name: webhook-certs
          mountPath: /etc/webhook/certs
          readOnly: true
      volumes:
      - name: webhook-certs
        secret:
          secretName: webhook-certs
---
apiVersion: v1
kind: Service
metadata:
  name: datadog-cluster-agent
  namespace: datadog
  labels:
    app: datadog-cluster-agent
spec:
  type: ClusterIP
  selector:
    app: datadog-cluster-agent
  ports:
  - port: 5005
    protocol: TCP
    targetPort: 5005
---
apiVersion: v1
kind: Service
metadata:
  name: datadog-cluster-agent-admission-controller
  namespace: datadog
  labels:
    app: datadog-cluster-agent
spec:
  selector:
    app: datadog-cluster-agent
  ports:
  - port: 443
    protocol: TCP
    targetPort: 443
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: datadog-cluster-agent
rules:
- apiGroups:
  - ""
  resources:
  - services
  - endpoints
  - pods
  - nodes
  - namespaces
  - componentstatuses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - "autoscaling"
  resources:
  - horizontalpodautoscalers
  verbs:
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - get
  - list
  - watch
  - create
- apiGroups:
  - "apps"
  resources:
  - deployments
  - replicasets
  - daemonsets
  - statefulsets
  verbs:
  - list
  - get
  - watch
- apiGroups:
  - "batch"
  resources:
  - cronjobs
  - jobs
  verbs:
  - list
  - get
  - watch
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses
  verbs:
  - list
  - get
  - watch
- apiGroups:
  - "datadoghq.com"
  resources:
  - "datadogmetrics"
  verbs:
  - "list"
  - "create"
  - "delete"
  - "watch"
- apiGroups:
  - "external.metrics.k8s.io"
  resources:
  - "*"
  verbs:
  - "list"
  - "get"
  - "watch"
- apiGroups:
  - admissionregistration.k8s.io
  resources:
  - mutatingwebhookconfigurations
  verbs:
  - get
  - list
  - watch
  - update
  - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: datadog-cluster-agent
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: datadog-cluster-agent
subjects:
- kind: ServiceAccount
  name: datadog-cluster-agent
  namespace: datadog
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: datadog-cluster-agent
  namespace: datadog
---
apiVersion: v1
kind: Secret
metadata:
  name: datadog-cluster-agent-token
  namespace: datadog
  labels:
    app: datadog-cluster-agent
type: Opaque
data:
  token: # Base64 encoded random token for cluster agent communication