version: 1
formatters:
  simple:
    format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  json:
    (): de_challenge.core.logging.JSONFormatter
handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: simple
    stream: ext://sys.stdout
  file:
    class: logging.FileHandler
    level: INFO
    formatter: json
    filename: logs/app.log
loggers:
  de_challenge:
    level: INFO
    handlers: [console, file]
    propagate: no
root:
  level: WARNING
  handlers: [console]
