groups:
  # Enterprise Business Metrics Alerting Rules
  - name: bmad-business-critical.rules
    interval: 60s
    rules:
      # =============================================
      # CRITICAL BUSINESS VALUE PROTECTION ($27.8M+)
      # =============================================
      
      # Overall Platform ROI Monitoring
      - alert: BMADPlatformROICriticalDrop
        expr: bmad_platform_roi_percentage < 70
        for: 10m
        labels:
          severity: critical
          component: business-roi
          business_impact: "27.8M"
          escalation: "immediate"
          stakeholder: "c-suite"
        annotations:
          summary: "CRITICAL: BMAD Platform ROI below 70%"
          description: "Overall platform ROI at {{ $value }}% - significant business value at risk"
          business_impact: "Total $27.8M+ business value compromised - immediate C-suite notification required"
          action_required: "Emergency platform review, resource reallocation, performance optimization"
          estimated_loss: "${{ with query \"(100 - bmad_platform_roi_percentage) * 278000\" }}{{ . | first | value | humanize }}{{ end }}/day"
          runbook_url: "https://runbooks.pwc.com/bmad-roi-critical"
          dashboard_url: "https://grafana.pwc.com/d/bmad-executive/bmad-executive-overview"

      # Business Value at Risk Monitoring
      - alert: BMADBusinessValueHighRisk
        expr: bmad_business_value_at_risk_dollars > 5000000
        for: 5m
        labels:
          severity: critical
          component: business-value
          business_impact: "multi-million"
          escalation: "immediate"
        annotations:
          summary: "HIGH BUSINESS VALUE AT RISK: ${{ $value }} million"
          description: "Over $5M in business value currently at risk across BMAD stories"
          business_impact: "Multiple business initiatives compromised"
          action_required: "Immediate assessment of failing stories, resource reallocation"
          affected_stories: "Review individual BMAD story health metrics"

      # =============================================
      # INDIVIDUAL STORY MONITORING
      # =============================================
      
      # Story 1: BI Dashboards ($2.5M) - Executive Decision Making
      - alert: BMADStory1DashboardCritical
        expr: bmad_story_health_score{story_id="1"} < 85
        for: 5m
        labels:
          severity: critical
          component: bi-dashboards
          story_id: "1"
          business_value: "2.5M"
          stakeholder: "executives"
        annotations:
          summary: "CRITICAL: BI Dashboard performance degraded"
          description: "Story 1 health at {{ $value }}% - Executive dashboards compromised"
          business_impact: "$2.5M BI story failing - Executive decision-making impacted"
          action_required: "Immediate dashboard performance optimization, data pipeline check"

      # Story 2: Data Quality ($1.8M) - Analytics Foundation
      - alert: BMADStory2DataQualityCritical
        expr: bmad_story_health_score{story_id="2"} < 80
        for: 3m
        labels:
          severity: critical
          component: data-quality
          story_id: "2"
          business_value: "1.8M"
          stakeholder: "data-teams"
        annotations:
          summary: "CRITICAL: Data Quality below acceptable threshold"
          description: "Story 2 health at {{ $value }}% - Data quality compromised"
          business_impact: "$1.8M Data Quality story failing - Analytics accuracy at risk"
          action_required: "Immediate data quality pipeline review, validation rule check"

      # Story 3: Security & Governance ($3.2M) - Compliance Risk
      - alert: BMADStory3SecurityCritical
        expr: bmad_story_health_score{story_id="3"} < 90
        for: 1m
        labels:
          severity: critical
          component: security-governance
          story_id: "3"
          business_value: "3.2M"
          stakeholder: "security-team"
          compliance: "gdpr-soc2"
        annotations:
          summary: "CRITICAL: Security & Governance compliance breach"
          description: "Story 3 health at {{ $value }}% - Security posture compromised"
          business_impact: "$3.2M Security story failing - Regulatory compliance at risk"
          action_required: "Immediate security review, compliance audit, risk assessment"

      # Story 4: API Performance ($2.1M) - <15ms SLA Critical
      - alert: BMADStory4APICriticalSLA
        expr: bmad_story_health_score{story_id="4"} < 85
        for: 2m
        labels:
          severity: critical
          component: api-performance
          story_id: "4"
          business_value: "2.1M"
          sla_tier: "15ms-critical"
        annotations:
          summary: "CRITICAL: <15ms API SLA breach"
          description: "Story 4 health at {{ $value }}% - API performance SLA violated"
          business_impact: "$2.1M API story failing - Critical response time SLA breached"
          action_required: "Immediate API optimization, caching review, infrastructure scaling"

      # Story 4.1: Mobile Analytics ($2.8M) - User Experience
      - alert: BMADStory41MobileCritical
        expr: bmad_story_health_score{story_id="4.1"} < 80
        for: 5m
        labels:
          severity: critical
          component: mobile-analytics
          story_id: "4.1"
          business_value: "2.8M"
          stakeholder: "product-team"
        annotations:
          summary: "CRITICAL: Mobile Analytics performance degraded"
          description: "Story 4.1 health at {{ $value }}% - Mobile user experience compromised"
          business_impact: "$2.8M Mobile story failing - User engagement at risk"
          action_required: "Mobile performance optimization, analytics pipeline review"

      # Story 4.2: AI/LLM Analytics ($3.5M) - Innovation Impact
      - alert: BMADStory42AICritical
        expr: bmad_story_health_score{story_id="4.2"} < 75
        for: 5m
        labels:
          severity: critical
          component: ai-llm-analytics
          story_id: "4.2"
          business_value: "3.5M"
          stakeholder: "ai-team"
          innovation: "high-value"
        annotations:
          summary: "CRITICAL: AI/LLM Analytics severely degraded"
          description: "Story 4.2 health at {{ $value }}% - AI capabilities compromised"
          business_impact: "$3.5M AI story failing - Innovation initiatives at risk"
          action_required: "Model performance review, infrastructure scaling, algorithm optimization"

      # Story 6: Advanced Security ($4.2M) - Highest Value Protection
      - alert: BMADStory6SecurityCritical
        expr: bmad_story_health_score{story_id="6"} < 88
        for: 1m
        labels:
          severity: critical
          component: advanced-security
          story_id: "6"
          business_value: "4.2M"
          stakeholder: "ciso"
          priority: "highest"
        annotations:
          summary: "CRITICAL: Advanced Security system failure"
          description: "Story 6 health at {{ $value }}% - Advanced security compromised"
          business_impact: "$4.2M Advanced Security story failing - Maximum security risk"
          action_required: "Emergency security response, threat assessment, system hardening"

      # Story 7: Real-time Streaming ($3.4M) - Data Velocity
      - alert: BMADStory7StreamingCritical
        expr: bmad_story_health_score{story_id="7"} < 82
        for: 3m
        labels:
          severity: critical
          component: streaming
          story_id: "7"
          business_value: "3.4M"
          stakeholder: "data-engineering"
        annotations:
          summary: "CRITICAL: Real-time Streaming pipeline failure"
          description: "Story 7 health at {{ $value }}% - Real-time data processing compromised"
          business_impact: "$3.4M Streaming story failing - Real-time insights unavailable"
          action_required: "Streaming pipeline restart, Kafka cluster review, data flow analysis"

      # Story 8: ML Operations ($6.4M) - Highest Value Story
      - alert: BMADStory8MLOpsCritical
        expr: bmad_story_health_score{story_id="8"} < 80
        for: 5m
        labels:
          severity: critical
          component: ml-operations
          story_id: "8"
          business_value: "6.4M"
          stakeholder: "ml-team"
          priority: "maximum"
        annotations:
          summary: "CRITICAL: ML Operations severely impacted - HIGHEST VALUE STORY"
          description: "Story 8 health at {{ $value }}% - ML Operations compromised"
          business_impact: "$6.4M ML Operations story failing - HIGHEST BUSINESS VALUE AT RISK"
          action_required: "Emergency ML pipeline review, model validation, infrastructure scaling"
          escalation_note: "Highest value story - immediate executive notification"

  # =============================================
  # BUSINESS KPI THRESHOLD MONITORING
  # =============================================
  - name: bmad-kpi-monitoring.rules
    interval: 60s
    rules:
      # Customer Satisfaction Impact
      - alert: CustomerSatisfactionCritical
        expr: customer_satisfaction_score < 75
        for: 10m
        labels:
          severity: critical
          component: business-kpi
          metric: "customer-satisfaction"
        annotations:
          summary: "Customer satisfaction critically low"
          description: "Customer satisfaction at {{ $value }}% - below critical threshold"
          business_impact: "Customer churn risk, revenue impact potential"

      # Daily Revenue Monitoring
      - alert: DailyRevenueSignificantDrop
        expr: (rate(daily_revenue_dollars[1h]) < rate(daily_revenue_dollars[1h] offset 24h) * 0.8)
        for: 2h
        labels:
          severity: critical
          component: business-kpi
          metric: "daily-revenue"
        annotations:
          summary: "Significant daily revenue drop detected"
          description: "Revenue 20% below yesterday's level for 2+ hours"
          business_impact: "Immediate revenue impact - investigation required"

      # Business KPI Composite Score
      - alert: BusinessKPICompositeScore
        expr: avg(business_kpi_value) < 75
        for: 15m
        labels:
          severity: warning
          component: business-kpi
          metric: "composite-score"
        annotations:
          summary: "Overall business KPIs below target"
          description: "Average business KPI score at {{ $value }}%"
          business_impact: "Multiple business metrics underperforming"

  # =============================================
  # ESCALATION AND RECOVERY MONITORING
  # =============================================
  - name: bmad-escalation.rules
    interval: 30s
    rules:
      # Multi-Story Failure (Cascading Impact)
      - alert: BMADMultiStoryFailure
        expr: count(bmad_story_health_score < 80) >= 3
        for: 5m
        labels:
          severity: critical
          component: platform-stability
          escalation: "emergency"
          stakeholder: "incident-commander"
        annotations:
          summary: "EMERGENCY: Multiple BMAD stories failing simultaneously"
          description: "{{ $value }} stories below 80% health - cascading failure detected"
          business_impact: "Platform-wide degradation - major business impact likely"
          action_required: "Activate incident response team, emergency coordination"
          estimated_impact: ">$10M total business value at risk"

      # Platform Health Critical
      - alert: BMADPlatformHealthEmergency
        expr: bmad_platform_health_score < 90
        for: 5m
        labels:
          severity: critical
          component: platform-health
          escalation: "emergency"
          stakeholder: "platform-team"
        annotations:
          summary: "EMERGENCY: BMAD Platform health critically degraded"
          description: "Overall platform health at {{ $value }}% - emergency response required"
          business_impact: "$27.8M+ total platform value at risk"
          action_required: "Emergency platform stabilization, all-hands response"

      # Recovery Time Monitoring
      - alert: BMADRecoveryTimeExceeded
        expr: time() - on() bmad_last_healthy_timestamp > 1800  # 30 minutes
        for: 0m
        labels:
          severity: critical
          component: recovery-time
          slo: "mttr-violation"
        annotations:
          summary: "CRITICAL: BMAD recovery time exceeding SLO"
          description: "Platform unhealthy for >30 minutes - MTTR SLO breach"
          business_impact: "Extended outage affecting all business operations"
          action_required: "Escalate to senior leadership, emergency procedures"

  # =============================================
  # PREDICTIVE BUSINESS ALERTS
  # =============================================
  - name: bmad-predictive.rules
    interval: 300s
    rules:
      # ROI Trend Analysis
      - alert: BMADROITrendingDown
        expr: delta(bmad_platform_roi_percentage[1h]) < -5
        for: 2h
        labels:
          severity: warning
          component: predictive-analysis
          trend: "declining"
        annotations:
          summary: "BMAD Platform ROI trending downward"
          description: "ROI decreased by {{ $value }}% over the last hour"
          business_impact: "Declining business value realization"
          action_required: "Investigate root causes, optimize underperforming stories"

      # Business Value Forecast
      - alert: BMADValueForecastRisk
        expr: predict_linear(bmad_platform_roi_percentage[4h], 24*3600) < 75
        for: 30m
        labels:
          severity: warning
          component: predictive-analysis
          forecast: "24h-risk"
        annotations:
          summary: "PREDICTIVE: BMAD value forecast shows risk"
          description: "Predicted ROI in 24h: {{ $value }}% - below target"
          business_impact: "Proactive intervention required"
          action_required: "Preventive optimization, story health improvement"

  # =============================================
  # SLA AND PERFORMANCE CRITICAL
  # =============================================
  - name: bmad-sla-critical.rules
    interval: 15s
    rules:
      # <15ms SLA Critical Monitoring
      - alert: BMADAPI15msSLAEmergency
        expr: histogram_quantile(0.95, rate(bmad_api_duration_seconds_bucket{story_id="4"}[1m])) > 0.025
        for: 2m
        labels:
          severity: critical
          component: api-sla
          story_id: "4"
          sla_tier: "15ms-emergency"
          business_value: "2.1M"
        annotations:
          summary: "EMERGENCY: <15ms SLA severely breached"
          description: "95th percentile API latency {{ $value }}ms - far exceeding 15ms SLA"
          business_impact: "$2.1M API story severely compromised"
          action_required: "Emergency API optimization, infrastructure scaling, traffic routing"
          
      # Data Quality SLA Critical
      - alert: BMADDataQualityEmergency
        expr: bmad_data_quality_score < 85
        for: 5m
        labels:
          severity: critical
          component: data-quality-sla
          story_id: "2"
          business_value: "1.8M"
        annotations:
          summary: "EMERGENCY: Data Quality SLA breach"
          description: "Data quality score {{ $value }}% - far below 95% SLA"
          business_impact: "$1.8M Data Quality story in emergency state"
          action_required: "Emergency data pipeline review, quality rule validation"

      # ML Model Accuracy Critical
      - alert: BMADMLAccuracyEmergency
        expr: bmad_ai_model_accuracy{story_id="4.2"} < 70
        for: 10m
        labels:
          severity: critical
          component: ml-accuracy
          story_id: "4.2"
          business_value: "3.5M"
        annotations:
          summary: "EMERGENCY: AI Model accuracy critically low"
          description: "AI model accuracy {{ $value }}% - emergency intervention required"
          business_impact: "$3.5M AI story in critical state"
          action_required: "Emergency model retraining, validation dataset review"

  # =============================================
  # COST AND EFFICIENCY MONITORING
  # =============================================
  - name: bmad-cost-efficiency.rules
    interval: 300s
    rules:
      # Cost-per-ROI Monitoring
      - alert: BMADCostEfficiencyDegraded
        expr: bmad_total_cost_dollars / (bmad_platform_roi_percentage/100) > 50000
        for: 1h
        labels:
          severity: warning
          component: cost-efficiency
          financial: "roi-cost-ratio"
        annotations:
          summary: "BMAD cost efficiency degraded"
          description: "Cost-per-ROI ratio exceeding targets"
          business_impact: "ROI efficiency declining, cost optimization needed"
          action_required: "Cost analysis, resource optimization review"

      # Resource Waste Detection
      - alert: BMADResourceWasteDetected
        expr: sum(resource_utilization_percentage) / count(resource_utilization_percentage) < 60
        for: 2h
        labels:
          severity: info
          component: resource-optimization
          efficiency: "low-utilization"
        annotations:
          summary: "BMAD resource utilization below efficiency targets"
          description: "Average resource utilization {{ $value }}% - optimization opportunity"
          business_impact: "Cost optimization potential identified"
          action_required: "Resource right-sizing, workload optimization"