global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # API service monitoring
  - job_name: 'pwc-api'
    static_configs:
      - targets: ['api:8000']
    metrics_path: /metrics
    scrape_interval: 30s
    
  # Dagster monitoring
  - job_name: 'dagster'
    static_configs:
      - targets: ['dagster:3000']
    metrics_path: /metrics
    scrape_interval: 60s
    
  # RabbitMQ monitoring  
  - job_name: 'rabbitmq'
    static_configs:
      - targets: ['rabbitmq:15692']
    metrics_path: /metrics
    scrape_interval: 30s
    
  # Kafka monitoring (JMX)
  - job_name: 'kafka'
    static_configs:
      - targets: ['kafka:9101']
    scrape_interval: 30s
    
  # PostgreSQL monitoring
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']
    scrape_interval: 60s
    
  # Spark monitoring
  - job_name: 'spark-master'
    static_configs:
      - targets: ['spark-master:8080']
    metrics_path: /metrics/master/json/
    scrape_interval: 60s
    
  # Typesense monitoring
  - job_name: 'typesense'
    static_configs:
      - targets: ['typesense:8108']
    metrics_path: /metrics
    scrape_interval: 60s