name: Claude Code

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  claude-code:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Claude Code Action
      uses: anthropics/claude-code-action@v1
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        claude-token: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}
        # Optional: Specify which files to analyze
        # include-patterns: |
        #   src/**/*.py
        #   tests/**/*.py
        # Optional: Specify files to exclude
        # exclude-patterns: |
        #   **/__pycache__/**
        #   **/node_modules/**
        
  quality-check:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Enhanced Code Quality Summary
      run: |
        echo "## Claude Code Quality Analysis" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "This workflow provides AI-powered code analysis using Claude Code." >> $GITHUB_STEP_SUMMARY
        echo "For detailed code quality metrics, see the main CI workflow." >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "### Recent Enhancements" >> $GITHUB_STEP_SUMMARY
        echo "- ✅ Enhanced Airflow DAG implementation" >> $GITHUB_STEP_SUMMARY
        echo "- ✅ Advanced Supabase integration" >> $GITHUB_STEP_SUMMARY
        echo "- ✅ Comprehensive error handling and recovery" >> $GITHUB_STEP_SUMMARY
        echo "- ✅ Production-ready monitoring and alerting" >> $GITHUB_STEP_SUMMARY
        echo "- ✅ Full backup/restore capabilities" >> $GITHUB_STEP_SUMMARY